aquarist-labs/ceph

- src/rgw/rgw_sal_dbstore.cc
- src/rgw/store/dbstore/common/dbstore.cc
This fix addresses a `radosgw` crash when using `dbstore` backend and deleting an object.
Please, refer to the linked issue for details about the issue itself and how to reproduce/test it. 
> rgw/dbstore: fixing a seg-fault when deleting an object

- src/rgw/store/dbstore/common/dbstore.cc
- src/rgw/store/dbstore/common/dbstore.h
- src/rgw/store/dbstore/sqlite/sqliteDB.cc
Have a look to the linked [ceph issue](https://tracker.ceph.com/issues/55288) and [s3gw issue](https://github.com/aquarist-labs/s3gw-core/issues/5) for details.
Please, be aware that this patch partially solves the issue.
GET computed set is now more correct because it does not include parent directory objects, but it will still wrongly
include objects in children directories.
Solving this entirely will probably involve design choices in dbstore.
This patch, by the way, resolves the major issue of `rm --recursive` deleting the entire content of the bucket.
Fixes: aquarist-labs/s3gw#5
Fixes: https://tracker.ceph.com/issues/55288
- Tests …
> rgw/dbstore: fix for GET operation.

- src/common/environment.cc
- src/common/environment.h
- src/rgw/rgw_sal.cc
Fixes: https://github.com/aquarist-labs/s3gw-core/issues/15
Signed-off-by: Volker Theile <vtheile@suse.com>
<details>
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>
> rgw: generate random API key and token on first run

- src/rgw/rgw_sal_dbstore.cc
- src/rgw/rgw_user.cc
- src/rgw/rgw_user.h
- src/rgw/store/dbstore/common/dbstore.cc
- src/rgw/store/dbstore/common/dbstore.h
- src/rgw/store/dbstore/sqlite/sqliteDB.cc
- src/rgw/store/dbstore/sqlite/sqliteDB.h
Adds a basic user listing to dbstore, so we can get the list of users using the REST API.
It also includes a fix so the REST API works. The fix has been picked up from upstream instead of committing mine. 
Fixes: https://github.com/aquarist-labs/s3gw-core/issues/42
Signed-off-by: 0xavi0 <xavi.garcia@suse.com>
<details>
- `jenkins test …
> rgw/dbstore: Add basic user list to dbstore

- src/rgw/rgw_sal_sfs.cc
- src/rgw/store/sfs/bucket.cc
- src/rgw/store/sfs/bucket.h
- src/rgw/store/sfs/sfs_user.cc
- src/rgw/store/sfs/sqlite/sqlite_users.cc
- src/rgw/store/sfs/user.cc
- src/test/rgw/sfs/test_rgw_sfs_sqlite_users.cc
This adds basic user management via rest api to `SFStore`.
Adds also a very basic versioning, increasing the version everytime the
user info is stored and checks for version when loading the user.
Added a few unittests for testing higher lever user management.
A smoke test will be added in a future PR but meanwhile you can test the user management rest api with something like this:
```python
import requests, json                                                                                         
from awsauth import S3Auth                                                                                    
ACCESS_KEY='test'                                                                             
SECRET_KEY='test'
URL='http://127.0.0.1:7480' …
```
> rgw/sfs: Add basic user management via rest api.

- src/rgw/store/sfs/CHANGELOG.md
- src/rgw/store/sfs/object.cc
- src/rgw/store/sfs/object.h
This implementation breaks S3 semantics because we do not allow a copy
to an existing object.
Fixes: aquarist-labs/s3gw#35
Signed-off-by: Joao Eduardo Luis \<joao@suse.com>
> rgw/sfs: basic object copy capabilities

- .github/workflows/test-radosgw.yml
- src/rgw/rgw_sal_sfs.h
- src/rgw/store/sfs/bucket.cc
- src/rgw/store/sfs/types.h
Creation time for buckets was correctly set on sqlite table but
when retrieving it, the data was not propagated during the object
copy chain.
Tested using s3cmd.
Fixes: https://github.com/aquarist-labs/s3gw/issues/63
- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.
<details>
<summary>Show available …
> rgw/sfs: Fixed bucket creation time always set at now() for SFS backend

- src/rgw/rgw_sal_sfs.h
- src/rgw/store/sfs/bucket.cc
- src/rgw/store/sfs/bucket.h
- src/rgw/store/sfs/sfs_bucket.cc
- src/rgw/store/sfs/types.h
- src/rgw/store/sfs/user.cc
System users are expected to receive an additional json response upon
bucket create operation.
Said response was not filled when a create bucket operation was
issued against a radosgw using sfs backend.
unit test is provided on a separate [PR](https://github.com/aquarist-labs/s3gw-tools/pull/158) on `s3gw-tools` repo 
For reference here is a _post-patch_ response produced with sfs be:
```
{
"bucket_info" : 
{
"bi_shard_hash_type" : 0,
"bucket" : 
{
"bucket_id" : "foo2.1661759760247537382",
"explicit_placement" : 
{
"data_extra_pool" : "",
"data_pool" : "",
"index_pool" : ""
},
"marker" : "foo2.1661759760247537382",
"name" : "foo2",
"tenant" : ""
},
"creation_time" : "2022-08-29T07:56:00.247537Z",
"flags" : 0,
"has_instance_obj" : false,
"has_website" : false,
"index_type" : 0, …
```
> rgw/sfs: filled bucket create json-response for system users

- src/rgw/CMakeLists.txt
- src/rgw/store/sfs/CMakeLists.txt
ceph/src/rgw/CMakeLists.txt does not build sfs backend directly anymore. 
It now contains only the directive to compile rgw_sal_dbstore.cc similarly with other SAL BEs.
Specific sfs build has been demanded to ceph/src/rgw/store/sfs/CMakeLists.txt
Fixes: https://github.com/aquarist-labs/s3gw/issues/95
- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.
- Documentation …
> rgw/sfs: reorganized cmake build for sfs backend

- src/rgw/store/sfs/CHANGELOG.md
- src/rgw/store/sfs/bucket.cc
- src/rgw/store/sfs/object.cc
- src/rgw/store/sfs/types.cc
- src/rgw/store/sfs/types.h
This allows the user to remove delete makers of objects which means basically undeleting objects.
It also shows delete markers correctly, so users are able to find what objects have been deleted.
This shows an object with 2 versions:
```bash
$ aws --endpoint=http://127.0.0.1:7480 s3api list-object-versions --bucket test                                            
{
"Versions": [
{
"ETag": "\"bf18c66f70054819415a46d7dc1bf34c\"",
"Size": 2297,
"StorageClass": "STANDARD",
"Key": "test-object3",
"VersionId": "waOECDbBj1.EmwbrkEFPNmMO79GA0DO",
"IsLatest": false,
"LastModified": "2022-09-14T13:35:59.566Z",
"Owner": {
"DisplayName": "M. Tester",
"ID": "testid"
}
},
{
"ETag": "\"bf18c66f70054819415a46d7dc1bf34c\"",
"Size": 2055,
"StorageClass": "STANDARD",
"Key": "test-object3",
"VersionId": …
```
> rgw/sfs: undelete objects implementation.

- src/rgw/rgw_sal_sfs.cc
- src/rgw/store/sfs/CHANGELOG.md
- src/test/rgw/sfs/test_rgw_sfs_sqlite_users.cc
This is a nasty hack to make `meta_list_keys_*()` work with both users and buckets.  What we _should_ do is create some extra class that knows how to do meta key listing of various types of object, and pass an instance of that around via the handle arguments to these functions. This would allow that as-yet-nonexistent class to keep track of max and truncated in `meta_list_keys_next()`.  Instead, the immediate nasty hack is to make handle point at a const string which indicates what type of metadata we're dealing with, then check that value and call an instance of the appropriate `rgw::sal::sfs::sqlite::SQLite*` class to get the metdata we care about.
Fixes: https://github.com/aquarist-labs/s3gw/issues/64
Signed-off-by: Tim Serong <tserong@suse.com>
- To sign and title your commits, please …
> rgw/sfs: add ability to list buckets via meta_list_*() functions

- src/rgw/rgw_sal_sfs.h
- src/rgw/store/sfs/CHANGELOG.md
- src/rgw/store/sfs/bucket.cc
- src/rgw/store/sfs/bucket.h
- src/rgw/store/sfs/sfs_bucket.cc
- src/rgw/store/sfs/sqlite/buckets/bucket_conversions.cc
- src/rgw/store/sfs/sqlite/buckets/bucket_definitions.h
- src/rgw/store/sfs/sqlite/dbconn.h
- src/rgw/store/sfs/types.cc
- src/rgw/store/sfs/types.h
- src/rgw/store/sfs/user.cc
- src/test/rgw/sfs/CMakeLists.txt
- src/test/rgw/sfs/test_rgw_sfs_sfs_bucket.cc
- src/test/rgw/sfs/test_rgw_sfs_sqlite_buckets.cc
rgw/sfs: ACL implementation
Implemented persistence for sfs bucket's ACL.
ACL is represented as an attribute with key: RGW_ATTR_ACL in attrs.
This means that an implementation for the field attrs must be provided
for sfs's buckets.
Details:
- Added battrs field to DBOPBucketInfo
- Implemented a google test ensuring proper encode/decode of battrs.
Same test also ensures fetching/storing from/to sqlite table.
- Implemented SFSBucket::set_acl()
- Implemented SFSBucket::merge_and_store_attrs()
~~- Introduced ScopedStoreBucketRefresher type implementing a RAII type for
refreshing buckets after completing a sqlite operation over a bucket.~~
- Some refactoring for rgw::sal::sfs::Bucket
- Introduced more generic instance variables:
- RGWBucketInfo info
- rgw::sal::Attrs attrs
- Removed instance …
> rgw/sfs: ACL implementation

- src/rgw/store/sfs/user.cc
- src/test/rgw/sfs/CMakeLists.txt
- src/test/rgw/sfs/rgw_sfs_utils.h
- src/test/rgw/sfs/test_rgw_sfs_sfs_user.cc
- src/test/rgw/sfs/test_rgw_sfs_sqlite_users.cc
Returns only the buckets owned by the SFSUser being called.
It also includes SFSUser tests.
This fix also affects the REST API user tests, as it fixes an issue in which the test fails if the store has any bucket.
Fixes: https://github.com/aquarist-labs/s3gw/issues/33
<details>
- `jenkins …
> rgw/sfs: Lists only the buckets owned by the user.

- src/rgw/store/sfs/CHANGELOG.md
- src/rgw/store/sfs/sqlite/dbconn.h
- src/rgw/store/sfs/sqlite/sqlite_users.cc
- src/rgw/store/sfs/sqlite/sqlite_users.h
- src/rgw/store/sfs/sqlite/users/users_conversions.cc
- src/rgw/store/sfs/sqlite/users/users_definitions.h
- src/test/rgw/sfs/test_rgw_sfs_sqlite_users.cc
Added a new table in sqlite's metadata to store the access keys related to a user.
That way, when querying by access key we query first that table to obtain the user id.
Could not implement in the user table itself because access keys are stored in a blob and we'd need to first decode the blob in order to query by access key.
Removed the helper columns in users table for access keys as it was only supporting the first key and it's no longer used.
Fixes: https://github.com/aquarist-labs/s3gw/issues/83
<details>
- …
> rgw/sfs: Get user by access_key when user has multiple keys

- src/rgw/store/sfs/CHANGELOG.md
- src/rgw/store/sfs/types.h
Because we were obtaining `obj_map_lock` (through `Bucket::finish()`) after acquiring `multipart_map_lock`, we introduced a circular dependency with `Bucket::abort_multiparts()`.
By ensuring we acquire the locks in the intended order (`obj_map_lock` first, then `multipart_part_lock`), matching the other function, we avoid getting stuck in a deadlock situation.
Signed-off-by: Joao Eduardo Luis \<joao@suse.com>
> rgw/sfs: fix circular lock dependency

- src/rgw/store/sfs/CHANGELOG.md
- src/rgw/store/sfs/sqlite/sqlite_users.cc
- src/rgw/store/sfs/sqlite/sqlite_users.h
A few user operations were not acquiring the connection lock, either at
all or at some stage of their execution. This was leading to operations
failing/asserting because the database would be locked by a concurrent
operation.
Signed-off-by: Joao Eduardo Luis \<joao@suse.com>
> rgw/sfs: ensure sqlite user ops hold required locks

- CMakeLists.txt
<details>
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>
> rgw/build: Add FMT_DEPRECATED_OSTREAM flag to avoid compilation issues

- src/rgw/store/sfs/CHANGELOG.md
- src/rgw/store/sfs/writer.cc
`mtime` parameter was logged but that's an output variable and might be `nullptr`.
Avoid logging it and check if it's `nullptr` before setting the value.
Fixes: https://github.com/aquarist-labs/s3gw/issues/191
Fixes: https://github.com/aquarist-labs/s3gw/issues/190
Fixes: https://github.com/aquarist-labs/s3gw/issues/182
- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.
- …
> rgw/sfs: Fix s3tests_boto3.functional.test_s3.test_post_object_* bug

- src/rgw/store/sfs/CHANGELOG.md
- src/rgw/store/sfs/bucket.cc
This patch allows a client to invoke stat_bucket call.
The eventual actual implementation will be addressed on a dedicated issue.
Fixes: https://github.com/aquarist-labs/s3gw/issues/159
- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.
<details>
- …
> rgw/sfs: make SFSBucket::update_container_stats return 0

- src/rgw/rgw_sal.cc
- src/rgw/store/sfs/CHANGELOG.md
- src/rgw/store/sfs/CMakeLists.txt
- src/rgw/store/sfs/sqlite/dbconn.cc
- src/rgw/store/sfs/sqlite/dbconn.h
- src/test/rgw/sfs/CMakeLists.txt
- src/test/rgw/sfs/compatibility_test_cases/columns_added.h
- src/test/rgw/sfs/compatibility_test_cases/columns_deleted.h
- src/test/rgw/sfs/compatibility_test_cases/optional_columns_added.h
- src/test/rgw/sfs/test_rgw_sfs_metadata_compatibility.cc
Adds a check on metadata compatibility when the `SFStore` initialises.
It creates a temporary copy of the metadata database and tries to sync the schema on it.
If there are issues (exeptions) or any table is dropped due to incompatibilities between the data base and the actual metadata schema it throws a `sqlite_sync_exception`.
The execption is catched when the `SFStore` is instantiated and the error is logged before exiting `rgw`.
Previous database is not altered as all checks are done in the temporary database so we don't have data loss.
Fixes: https://github.com/aquarist-labs/s3gw/issues/178
<details>
<summary>Show …
> rgw/sfs: Detect metadata compatibility issues.

- src/rgw/store/sfs/CHANGELOG.md
- src/rgw/store/sfs/object.cc
- src/rgw/store/sfs/types.cc
- src/rgw/store/sfs/types.h
Adds code for adding a delete marker when deleting an object that doesn't exist.
According to the [AWS documentation](https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-object.html) when deleting an object it should reply with no errors even if the object doesn't exist.
This means we create a delete-marker version for the object when versioning is enabled.
This also fixes the s3-test
test_versioning_multi_object_delete_with_marker_create which is exactly that test case.
**Note**
When undeleting delete markers (or deleting all versions of an object), if the object ends up having no version we just remove it from the in-memory objects map.
This is something that also could happen manually deleting all the version for an object and it was causing a segfault due to a `ceph_assert` …
> rgw/sfs: Generate delete markers for non existing objects

- src/rgw/rgw_sal.cc
- src/rgw/rgw_sal_sfs.cc
- src/rgw/rgw_sal_sfs.h
- src/rgw/store/sfs/CHANGELOG.md
- src/rgw/store/sfs/CMakeLists.txt
- src/rgw/store/sfs/sfs_gc.cc
- src/rgw/store/sfs/sfs_gc.h
- src/rgw/store/sfs/sqlite/sqlite_buckets.cc
- src/rgw/store/sfs/sqlite/sqlite_buckets.h
- src/rgw/store/sfs/types.cc
- src/rgw/store/sfs/types.h
- src/test/rgw/sfs/CMakeLists.txt
- src/test/rgw/sfs/test_rgw_sfs_gc.cc
- src/test/rgw/sfs/test_rgw_sfs_sqlite_buckets.cc
This adds an initial GC approach just starting a thread and running
a basic remove deleted buckets operation.
The implementation of how the thread is started and stopped are taken from rgw's code for consistency across stores and thinking on the possible merge upstream. 
It uses 2 parameters from rgw:
- `rgw_gc_processor_period` : defines the time GC waits to be triggered (in seconds)
- `rgw_gc_max_objs` : defines the maximum number of items the GC can remove per iteration.
Any possible actions done to the `sqlite` metadata is considered an item (object) when taking into account the maxium number of items to be processed in a single iteration as those actions block the metadata database.
Fixes: https://github.com/aquarist-labs/s3gw/issues/165
Signed-off-by: Xavi Garcia …
> rgw/sfs: Initial Garbage collector thread.

- doc/radosgw/s3/commons.rst
- src/common/options/rgw.yaml.in
- src/rgw/rgw_rest.cc
Note:
This is the exact cherry-picked commit taken from the upstream [PR](https://github.com/ceph/ceph/pull/48554) 
Given that this is patching a generic non-sfs behavior, should we update the sfs's CHANGELOG.md ?
commit message:
rgw_dns_name configuration option has extended to define multiple domain values.
This option is now interpreted as a comma separated list of DNS names.
Example:
rgw_dns_name = cname.domain.com,cname2.domain2.com, cname3.domain3.com
- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - …
> rgw: add multivalue support to rgw_dns_name config option

- etc/sysconfig/s3gw
- s3gw.spec
- systemd/s3gw.service
This commit adds an s3gw.spec file for building a standalone s3gw RPM, along with a systemd unit file and sysconfig file to tweak settings (e.g. local data directory).  The systemd unit file and sysconfig file are not necessary or even desirable when running containerized, but make sense in the context of a standalone package.
s3gw.spec is based on the existing ceph.spec.in, but instead of creating a ceph package plus a bunch of library packages and other subpackages, s3gw.spec creates a single RPM containing the radosgw binary, librados, libradosgw and libceph-common.  The s3gw RPM is set to conflict with ceph-radosgw and librados2, to avoid accidental installation alongside (or on top of!) a regular ceph deployment.
With this, we can do package builds on OBS with pretty much nothing …
> Add s3gw specfile, systemd service and sysconfig file

- .github/workflows/build-test-radosgw.yml
This fixes the CI to show the results of the unit tests. It was running the contained with `-d`, so the results were not shown in the workflow logs.
Fixes: https://github.com/aquarist-labs/s3gw/issues/283
<details>
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume …
> ci: Don't run sfs unit tests in the background

- src/CMakeLists.txt
Fix git version parsing in CMake.
With the `ENABLE_GIT_VERSION` option set to `ON`, CMake will extract version information for building the version string from git. After extracting, it will also process the information found. Processing in this case means removing a leading `v` character. Instead of removing the first character (actually first byte) regardless of what it is, use a regex to ensure just a leading `v` is removed. This allows for version strings like `s3gw-v0.10.0` to propagate correctly into the version information compiled into radosgw without being truncated accidentally.
Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>
- If …
> build: fix git version parsing in cmake

- src/rgw/rgw_sal_sfs.cc
- src/rgw/store/sfs/sfs_gc.cc
- src/rgw/store/sfs/sfs_gc.h
Fix the order of initialization and use of the SFSGC. The worker thread can not start running until the SFSGC object has been completely allocated, because the SFSGC object is the dout prefix provider and a pointer to the SFSGC instance would be invalid until the constructor has finished.
Since the worker thread might want to print something out, this would resuult in an invalid pointer dereference.
Upon stopping, the SFSGC must query the worker thread if it has started, because an SFSGC instance could be created without calling `SFSGC::initialize()`. In this case calling `join()` on the worker has to be prevented.
Fixes bugs introduced in:
f7dbf8bd3d806c8887e42975b56a01e45ccfef5a
Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>
- To sign and title your commits, please refer to …
> rgw: fix order of initialization and use in SFSGC
